services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratp_pmr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - ratp_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  notifier:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: builder
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/ratp_pmr
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ratp_pmr
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
    command: sh -c "while true; do node --import tsx scripts/processNotificationQueue.ts; sleep 30; done"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ratp_network

  web:
    extra_hosts:
      - "host.docker.internal:192.168.1.23"
    build:
      context: .
      dockerfile: Dockerfile.web
      target: runner
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/ratp_pmr
    user: "${UID}:${GID}"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ratp_pmr
      NEXT_PUBLIC_WS_URL: http://host.docker.internal:3001
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run dev || tail -f /dev/null"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ratp_network

  ws:
    build:
      context: .
      dockerfile: ./ws-server/Dockerfile.ws
    ports:
      - "3001:3001"
    volumes:
      - ./ws-server:/ws
      - /ws/node_modules
    command: npm run start
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - ratp_network

volumes:
  pgdata:

networks:
  ratp_network:
    driver: bridge
